### ISSUE TITLE
RFE: Add toml input/output support to nmstatectl

### ISSUE THREAD

**Issue by tyll** [nmstate/nmstate#1362]
@Conan-Kudo proposed to add toml support for nmstatectl besides yaml and json. It would be nice to check if this is possible and to implement this as an optional format (maybe as an optional dependency).

**Comment by SudhanAruna** [comment]
Can I work on this?

**Comment by ffmancera** [comment]
Hello @SudhanAruna, yes is a nice task to work on. Please notice it will need some investigation, we need to find a way to do not require a new dependency. I will be around on IRC so please, let me know if you have any question. Thanks!

**Comment by SudhanAruna** [comment]
> Hello @SudhanAruna, yes is a nice task to work on. Please notice it will need some investigation, we need to find a way to do not require a new dependency. I will be around on IRC so please, let me know if you have any question. Thanks!

Okay sure

**Comment by cathay4t** [comment]
I dislike TOML output format with reason state at https://github.com/nmstate/nmstate/pull/1425#pullrequestreview-535874721

The `nmstatectl` is for test or script use only. User who want to TOML format, they can easily convert yaml/json to TOML by themselves.

Sorry, I should state my comments before the work been started.

**Comment by cathay4t** [comment]
The issue https://github.com/alexcrichton/toml-rs/issues/258 and https://github.com/toml-lang/toml/issues/379 shows the TOML
is not well defined or stabled.

It might be good for simple config files, but not for network state with nested data structure.

**Comment by Conan-Kudo** [comment]
@cathay4t Any you're okay with the insanity around YAML instead? That seems pretty bad. Also, NetworkManager *itself* uses an INI-style configuration already, which TOML is a direct superset of.

**Comment by EdDev** [comment]
I agree with @cathay4t , embedding support for TOML into `nmstatectl` has limited value and can be workaround using an external tool/script that can just convert yaml/json to TOML and vice versa.

JSON and YAML are extensively used to communicate information between application and both are suited as an API format for `libnmstate`.
As I see it, TOML has only usability as a configuration file that can be loaded and not as an API format.
Therefore, I see no advantage of using it over the existing formats.

If there is a real use case here, please share it (I could not see it in this issue description).

**Comment by Conan-Kudo** [comment]
Copied from the pull request:

There are three reasons, as I brought up with the team in DevConf.US:

1. The general attitude around YAML based configuration that most systems administrators that I've talked to is unblemished hatred. YAML makes it difficult for people to be sure they have gotten the configuration file correct. It's not just a matter of whitespace indentation, but all the other weird properties with YAML. At least at work, that experience has been formed by the problems experienced with Netplan configuration, which is YAML.

2. JSON does not support comments. This makes leaving notes and conveying meaning essentially impossible.

3. TOML is very similar to NetworkManager's own native configuration format, while still internally representing as a dictionary structure. That makes it very easy to plug into nmstate and make it useful for people to take their configurations and translate it a level up if they're using nmstate to configure NetworkManager.

Also, you should not be using anything but JSON as interchange between applications anyway. YAML is too brittle and causes issues depending on how YAML is being parsed (since YAML parsing is _very hard_ and inconsistent) and TOML is often too dense for streaming between applications.

**Comment by EdDev** [comment]
> Copied from the pull request:
> 
> There are three reasons, as I brought up with the team in DevConf.US:
> 
>     1. The general attitude around YAML based configuration that most systems administrators that I've talked to is unblemished hatred. YAML makes it difficult for people to be sure they have gotten the configuration file correct. It's not just a matter of whitespace indentation, but all the other weird properties with YAML. At least at work, that experience has been formed by the problems experienced with Netplan configuration, which is YAML.

YAML has been established well in the [Kubernetes](https://kubernetes.io/) community which makes discussions about its weakness weaker.
It landed well there mainly because the configurations have been lead by programs that generated the configuration files
and not by humans manually.

I think your argument here is strong for human interaction with the configuration files that are applied for Nmstate to process. But Nmstate consumption is targeted to applications and not manual edit of the state using nmstatectl.

> 
>     2. JSON does not support comments. This makes leaving notes and conveying meaning essentially impossible.
> 
>     3. TOML is very similar to NetworkManager's own native configuration format, while still internally representing as a dictionary structure. That makes it very easy to plug into nmstate and make it useful for people to take their configurations and translate it a level up if they're using nmstate to configure NetworkManager.
> 
> 
> Also, you should not be using anything but JSON as interchange between applications anyway. YAML is too brittle and causes issues depending on how YAML is being parsed (since YAML parsing is _very hard_ and inconsistent) and TOML is often too dense for streaming between applications.

As mentioned before, it is actually commonly used by marshaling and unmarshaling the data unto code structures.
But as this is not the core reasoning for using TOML, I think we can try and focus on the actual reasoning.

If TOML is a real use case you see needed for managing manually configuration files for Nmstate to process, I think we can try and find a middle ground to both not burden on the Nmstate core project and in the same time support users like you to get things done.
I have two alternatives here:
- Provide a pluggable interpreter that can be integrated into nmstatectl.
- Provide a simple translator that inputs a TOML format and emits a JSON one (and vice versa if needed).

Both solutions will leave the burden of maintenance and documentation under a 3rd party repo and we can reference it from our landing page.
If we will see wide spread usage of it, then we can consider adding the repo under the Nmstate organization.

WDYT?

**Comment by Conan-Kudo** [comment]
> YAML has been established well in the Kubernetes community which makes discussions about its weakness weaker.
It landed well there mainly because the configurations have been lead by programs that generated the configuration files
and not by humans manually.
>
> I think your argument here is strong for human interaction with the configuration files that are applied for Nmstate to process. But Nmstate consumption is targeted to applications and not manual edit of the state using nmstatectl.

I think this is _not_ how people are going to use NMState primarily. Outside of the Kubernetes model, where it does make sense to use YAML as an input, I expect that the vast majority of network interactions will be human driven in some manner. This is further reinforced by the website itself not really talking about using it as an API, but more as a tool itself to define network configuration.

Regardless, I want to address your two options:

> * Provide a pluggable interpreter that can be integrated into nmstatectl.

This seems to be architecturally overkill, but if it leads to NMState being able to natively handle TOML based configuration and the human operator does not have care about it beyond that point, then that's fine. I will note that at least one CentOS SIG has already pulled in `python-toml`, so I expect that the "problem" of this dependency isn't likely to be one in the near future.

> * Provide a simple translator that inputs a TOML format and emits a JSON one (and vice versa if needed).

This would be a problem, because you'd lose comments and other human artifacts in the process. The goal here is to make NMState usable and attractive compared to other options.

**Comment by EdDev** [comment]
> I think this is not how people are going to use NMState primarily. Outside of the Kubernetes model, where it does make sense to use YAML as an input, I expect that the vast majority of network interactions will be human driven in some manner. This is further reinforced by the website itself not really talking about using it as an API, but more as a tool itself to define network configuration.

The current two users of Nmstate in production are [KubeVirt](https://kubevirt.io/) and [oVirt](https://www.ovirt.org/), both use it as an API abstraction layer to the OS network configuration.
`nmstatectl` was not considered a core tool, but we are highly interested in maintaining it anyway.

If your prediction will materialize, and we will have users who prefer to use the tool for individual configuration on nodes, we will probably adjust as needed.

 >> provide a pluggable interpreter

> This seems to be architecturally overkill, but if it leads to NMState being able to natively handle TOML based configuration and the human operator does not have care about it beyond that point, then that's fine.

Making everyone happy is hard, but in this case I do not see the big complexity. We already have two formats, structuring it in a way to load an external implementation should not be that hard. But lets see what others think.

>> Provide a simple translator

> This would be a problem, because you'd lose comments and other human artifacts in the process. The goal here is to make NMState usable and attractive compared to other options.

Sorry, I missed how we will loose comments here. Given you have a TOML file `example.toml` with all comments, you will run:
`toml2json -f example.toml | nmstatectl` and the config will be applied (or not). No one will remove the original comments.
If you are talking about the report part not including the comments, then the current solution is not expected to support it as well.

BTW, there is a `description` field for the interfaces which you can use to add persisted comments about the interface if that helps.

**Comment by cathay4t** [comment]
> @cathay4t Any you're okay with the insanity around YAML instead? That seems pretty bad. Also, NetworkManager _itself_ uses an INI-style configuration already, which TOML is a direct superset of.

I failed to understand the `That seems pretty bad`. Please elaborate it.

YAML looks good for CLI output and dumping to file.
JSON is well tested as IPC format in open source world.

The TOML official says:

    The TOML aims to be a minimal __configuration file__ format. 

But still I find TOML file hard to edit for complex network state, for example OVS bonding or linux bridge vlan filtering.

Nmstate is __not__ subproject of NetworkManager, we don't have to use what ever NetworkManager chose.

**Comment by cathay4t** [comment]
> > The dependency `python3-toml` does not exists in RHEL 8 official repo. I don't want to be maintainer of `python3-toml` in RHEL 8 just for a CLI output format.
> 
> Good news, I suppose: Most of the Python ecosystem increasingly depends on that module anyway, and the Python team already maintains it in Fedora for supporting things like [PEP 518 `pyproject.toml`](https://www.python.org/dev/peps/pep-0518/). So I don't think you'd be alone in maintaining it for RHEL anyway.

I only revoke my rejection after RHEL 8 included `python3-toml` in `BaseOS` or `AppStream` repo unless something magic don't require me to add new package to RHEL. Add new package to RHEL takes much much more effort than Fedora.

**Comment by tyll** [comment]
> I only revoke my rejection after RHEL 8 included `python3-toml` in `BaseOS` or `AppStream` repo unless something magic don't require me to add new package to RHEL. Add new package to RHEL takes much much more effort than Fedora.

To check if I understand correctly: If the toml dependency is optional, you would be fine with the feature?

**Comment by cathay4t** [comment]
Even that's optional, it still require effort on maintaining it which can be saved if user just use their own tool for converting.

Do we have any benefit supporting TOML natively in nmstatectl?
