### ISSUE TITLE
Python library naming.

### ISSUE THREAD

**Issue by cathay4t** [nmstate/nmstate#157]
I created the Fedora RPM for nmstate at:
* Fedora: https://copr.fedorainfracloud.org/coprs/cathay4t/nmstate/
* RHEL: https://copr.fedorainfracloud.org/coprs/cathay4t/nmstate-el/

The package is named as `python3-nmstate` while the python library is `libnmstate`.

Just needed to be clarified:
 * Since the whole project is about API library, should we just name the python binding/library as
   `nmstate`?

**Comment by tyll** [comment]
Great work Gris! Renaming the library to nmstate makes sense to me.

About the RPMs:
- it would be great to run the unit tests in %check if all dependencies for this are available
- The README.md should probably be packaged as %doc
- It would be great to have also a python2 version for EPEL - would you prefer a second SPEC or use some %ifs?
- Currently there is only a python3-nmstate package but not nmstate package or Provides. Does it maybe make sense to package nmstatectl in a nmstate package and only the lib in python3-nmstate?

**Comment by cathay4t** [comment]
@EdDev Any comments?

**Comment by cathay4t** [comment]
> About the RPMs:
> 
>     * it would be great to run the unit tests in %check if all dependencies for this are available
I will add that section.
> 
>     * The README.md should probably be packaged as %doc
Will do.
> 
>     * It would be great to have also a python2 version for EPEL - would you prefer a second SPEC or use some %ifs?
I prefer a second SPEC to keep it tidy.
> 
>     * Currently there is only a python3-nmstate package but not nmstate package or Provides. Does it maybe make sense to package nmstatectl in a nmstate package and only the lib in python3-nmstate?

Will split them.

**Comment by EdDev** [comment]
Thanks, this is great!

> - it would be great to run the unit tests in %check if all dependencies for this are available

The build system usually does not have all the unit tests prerequisites (mainly true for Centos/RHEL). I do not think we should mix the two.

> - It would be great to have also a python2 version for EPEL - would you prefer a second SPEC or use some %ifs?

If we can have two spec files in the project it will be great. VDSM uses one, but I prefer the split as well.

> - Currently there is only a python3-nmstate package but not nmstate package or Provides. Does it maybe make sense to package nmstatectl in a nmstate package and only the lib in python3-nmstate?

I prefer to have `python{2,3}-nmstate as a meta package (which installs the lib and ctl). But I do not think it is a must at all.

I would like to see `python{2,3}-libnmstate` and `python(2,3}-nmstatectl`.
The `ctl` one depends on the `lib` one.

As I recall, we have not used `nmstate` as the package because it does not work well with the `pbr` which was used to package the lib and ctl together. Per what I understood, the only other option was to split the lib and ctl into different repos, which I dislike at the moment.

Are you going to post the spec and procedure?

**Comment by tyll** [comment]
Since we are removing pbr, we can reconsider to name the library nmstate. For nmstatectl, we only need one package named nmstatectl, that can depend on python2-(lib)nmstate or python3-(lib)nmstate. But the python version does not need to be in the package name for the ctl.

**Comment by cathay4t** [comment]
Closing as we all agreed on current RPM naming scheme.
