### ISSUE TITLE
Can't disable a NIC through nmstate config

### ISSUE THREAD

**Issue by nmagnezi** [nmstate/nmstate#1946]
## Describe the bug
This bug was initially reported in [Bugzilla 2095173
](https://bugzilla.redhat.com/show_bug.cgi?id=2095173).

A simple config such as:
```yaml
interfaces:
- mac-address: de:ad:bb:ef:00:25
  name: ens4
  state: down
```
Results an empty configuration.

## Nmstate version
- Version 1.3.0

## NetworkManager version
- N / A

## Platform
- N / A

## How reproducible
- 100%

## Steps to Reproduce
Use the above-mentioned config with `nmstatectl gc`

## Nmstate output
- Expected output:
A valid config.
- Current output:
`--- {}`
### Additional context
This seems to work okay in later versions such as 2.1.2 - should this be backported to 1.3.x?
Copied over from [my comment in Bugzilla 2095173](https://bugzilla.redhat.com/show_bug.cgi?id=2095173#c5):

**1.3.0 version:**
```sh
[nmagnezi@nmagnezi ~]$ nmstatectl --version
1.3.0
[nmagnezi@nmagnezi ~]$ nmstatectl gc test1
--- {}
```

**2.1.2 version:**

```sh
[nmagnezi@rdu-infra-edge-03 ~]$ nmstatectl --version
nmstatectl 2.1.2
[nmagnezi@rdu-infra-edge-03 ~]$ nmstatectl gc test1
[2022-06-27T08:08:58Z WARN  nmstate::ifaces::inter_ifaces] Setting unknown type interface ens4 to ethernet
[2022-06-27T08:08:58Z INFO  nmstate::ifaces::inter_ifaces] Adding interface ens4 with type ethernet
---
NetworkManager:
  - - ens4.nmconnection
    - "[connection]\nautoconnect=true\nautoconnect-slaves=-1\nid=ens4\ninterface-name=ens4\ntype=802-3-ethernet\nuuid=739065e7-6e8f-5205-923f-530d8fd646f9\n\n[ipv4]\nmethod=disabled\n\n[ipv6]\nmethod=disabled\n"
```

**Comment by ffmancera** [comment]
Thank you for reporting this. Yes, this should be backported.

**Comment by cathay4t** [comment]
This is copy from what I state in bugzilla:


The GC(generate configuration) mode of nmstate does not support `state: down` or `state: absent` of interface. It is a bug to nmstate 2.x when generating output for `state:down` interface.

To solve your problem:
 * If you desire IPv4 and/or IPv6 disabled for certain interface, you state so with `state: up` for GC mode.
 * If you desire physical link down for certain interface, `state: down` to `nmstatectl apply` or `ip link set eth1 down` can help, but you have to run it after every reboot. Because there is no way in NetworkManager keyfile says I want this interface in link down state.

**Comment by ffmancera** [comment]
As this is not doable for gen_conf I am closing this issue. Please, re-open it if you consider we should work on this. Thanks!
