### ISSUE TITLE
Compare with https://netplan.io/ in README

### ISSUE THREAD

**Issue by cgwalters** [nmstate/nmstate#46]
It'd be good to have a brief discussion (from your perspective) in the `README.md` with a comparison to <https://netplan.io/>.

**Comment by EdDev** [comment]
This is interesting, I will have a look.

**Comment by EdDev** [comment]
I will try to summarize what I found different below.
- Desired vs Current state: nmstate is built to describe the desired state and present the current state of the system in the same format, in order to allow a controller/manager to control the system state. netplan seems to avoid this intentionally, handling only the desired state with no regards to the actual outcome (current state).
Changes to a system state may not be reflected back, which is limiting for several scenarios.
- schema: nmstate attempts to mimic the telco netconf/yang schema whenever it can, grouping the configuration based on the interfaces/devices. netplan seems to follow a different path, by grouping based on the interface types and then sub-grouping on the interfaces that belong to the type.
- backend/provider definition: With netplan, the provider is specified in the desired state, while nmstate will prefer to control it in a different context (allowing providers to register as plugins and specifying which entities they control). With that said, nmstate is not yet there, but the use case of openstack vendor specific interfaces will need to be addresses pretty soon.
Mixing the desired state and the definition of which provider implements it in the same config set is less optimal.
- Transaction: nmstate is aimed to support transactional changes, where a state is either changed or not changed at all. A configuration change should not end up in an intermediate state. Not sure if netplan is looking for such an option.
- Package/Distribution: nmstate is python based at the moment, which is considered a disadvantage in terms of packaging/distribution.
- Events: nmstate is planned to support triggering events if asked for, supporting systems where the current state is monitored by controllers.

**Comment by EdDev** [comment]
I think the comparison fits a blog or an issue ticket like this one.
Adding such a conversation to a README is not a good fit IMO.

Closing this issue for now.

**Comment by sskras** [comment]
@EdDev: were the comparison results published somewhere (or just being lost in this ticket)?
In the positive case the link to such blog page would still be nice to include in the README.
