### ISSUE TITLE
nmstate 0.3: Enforce keyword args for apply(), commit(), rollback() and show()

### ISSUE THREAD

**Issue by tyll** [nmstate/nmstate#786]
This is a follow-up, to #635 once nmstate 0.3 is branched. This needs to revert the changes for warnings from #635 and add `*` to the function definitions instead.

**Comment by adwait-thattey** [comment]
Hello, Can I try this one out?

**Comment by adwait-thattey** [comment]
If I understood this correctly, the function definitions for APIs `apply()`, `commit()`, `rollback()` and `show()` need to be modified with `'*'` at the beginning so that positional arguments are not allowed and the current warning decorators applied on those APIs need to be removed

If this is fine, I will make a PR with the changes

**Comment by tyll** [comment]
> Hello, Can I try this one out?

Thank you, please go ahead.

> If I understood this correctly, the function definitions for APIs `apply()`, `commit()`, `rollback()` and `show()` need to be modified with `'*'` at the beginning so that positional arguments are not allowed and the current warning decorators applied on those APIs need to be removed

Sounds good. Also the tests need to be adjusted.

**Comment by adwait-thattey** [comment]
I have made the changes but I have left the file [deprecation.py](https://github.com/nmstate/nmstate/blob/master/libnmstate/deprecation.py) as it is. Should I delete that file?

**Comment by tyll** [comment]
> I have made the changes but I have left the file [deprecation.py](https://github.com/nmstate/nmstate/blob/master/libnmstate/deprecation.py) as it is. Should I delete that file?

Yes, please delete it.
