### ISSUE TITLE
README.install.md does not specify all dependencies for building?

### ISSUE THREAD

**Issue by IsmayilMirzali** [nmstate/nmstate#881]
OS: Fedora 31 running on Kernel 5.5.7

The readme does not seem to specify the ```dbus-devel``` and ```cairo-gobject-devel``` dependencies. Very minor issue, but just wanted to note it. (Can probably do a PR on the install readme and add anything new I may come across)

**Comment by ffmancera** [comment]
AFAIK, if you are using the rpm package you should be able to install it just with `dnf install nmstate`. It should not require to install any dependency manually

**Comment by tyll** [comment]
@IsmayilMirzali thank you for your report. Please provide the exact commands that you tried and the errors that you saw. Which installation method did you try?

**Comment by IsmayilMirzali** [comment]
> @IsmayilMirzali thank you for your report. Please provide the exact commands that you tried and the errors that you saw. Which installation method did you try?

I was trying to run ```pip install -r requirements.txt``` in a venv but the command kept failing because of missing dependencies. ```dbus-devel``` and ```cairo-gobject-devel``` were two of those. (I also had to get ```python3-devel``` but that's obvious) (Python version in venv is ```3.7.6```)

**Comment by tyll** [comment]
> I was trying to run `pip install -r requirements.txt` in a venv but the command kept failing because of missing dependencies. `dbus-devel` and `cairo-gobject-devel` were two of those. (I also had to get `python3-devel` but that's obvious) (Python version in venv is `3.7.6`)

It should work when you install python3-dbus python3-gobject-base as mentioned in https://github.com/nmstate/nmstate/blob/master/README.install.md#install-nmstate-from-pypi and create the venv with `--system-site-packages`. This is required because the two packages are binary python modules and not pure-python modules.

An alternative to install the dependencies for the binary packages would be to run `yum builddep python3-dbus python3-gobject-base`, then pip should be able to compile them in the venv.

Please note, that Nmstate from master currently requires a NetworkManager version that is not available on Fedora 31 but for example at: https://copr.fedorainfracloud.org/coprs/networkmanager/NetworkManager-1.22-git/

If you like to clarify the README, please go ahead.

**Comment by IsmayilMirzali** [comment]
> > I was trying to run `pip install -r requirements.txt` in a venv but the command kept failing because of missing dependencies. `dbus-devel` and `cairo-gobject-devel` were two of those. (I also had to get `python3-devel` but that's obvious) (Python version in venv is `3.7.6`)
> 
> It should work when you install python3-dbus python3-gobject-base as mentioned in https://github.com/nmstate/nmstate/blob/master/README.install.md#install-nmstate-from-pypi and create the venv with `--system-site-packages`. This is required because the two packages are binary python modules and not pure-python modules.
> 
> An alternative to install the dependencies for the binary packages would be to run `yum builddep python3-dbus python3-gobject-base`, then pip should be able to compile them in the venv.
> 
> Please note, that Nmstate from master currently requires a NetworkManager version that is not available on Fedora 31 but for example at: https://copr.fedorainfracloud.org/coprs/networkmanager/NetworkManager-1.22-git/
> 
> If you like to clarify the README, please go ahead.

Thank you so much for the info. I'll try to clarify this in the README.
