### ISSUE TITLE
Rewrite the README.release.md to a template for a task list

### ISSUE THREAD

**Issue by tyll** [nmstate/nmstate#907]
Rewrite [README.release.md](https://github.com/nmstate/nmstate/blob/master/packaging/README.release.md) to a [task list](https://help.github.com/en/github/managing-your-work-on-github/about-task-lists)

Ideally, this would be a template for new issues.

**Comment by ffmancera** [comment]
Good idea! Thanks!

**Comment by pavitra14** [comment]
I would like to contribute to this issue, 
I'm a little confused on how exactly to rewrite the issue.
A little help would be great!

**Comment by ffmancera** [comment]
> 
> 
> I would like to contribute to this issue,
> I'm a little confused on how exactly to rewrite the issue.
> A little help would be great!

Sure, that would be awesome.

Currently, [README.release.md](https://github.com/nmstate/nmstate/blob/master/packaging/README.release.md) contains the instructions to do a release. The idea is to transform that markdown file into a template in order to use it in new release issues.

The new template should be a task list, so we could mark the different steps as done when releasing.

If you have any other question, please let me know. Please, @tyll could you assign this to @pavitra14? Thanks!

**Comment by pavitra14** [comment]
Pushed changes to #912 PR
